/* DDBB */
CREATE DATABASE IF NOT EXISTS handicraft DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

/* TABLE USERS */
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(20) NOT NULL,
  name VARCHAR(30) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

/* TABLE HANDICRAFTS */
CREATE TABLE IF NOT EXISTS handicrafts (
  id INT NOT NULL AUTO_INCREMENT,
  date_created DATE NOT NULL,
  user_id VARCHAR(20) NOT NULL,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(255) NOT NULL,
  is_fragile BIT(1) NOT NULL,
  weight_grams FLOAT NULL DEFAULT NULL,
  image_filename VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

/* RELATE TABLES USERS AND HANDICRAFTS: SET FOREIGN KEY AS INDEX, ADD FOREIGN KEY, RESTRICT ON DELETE, CASCADE ON UPDATE */
ALTER TABLE
  handicrafts
ADD
  INDEX(user_id);

ALTER TABLE
  handicrafts
ADD
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE;